version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo In the pre_build phase...
      - chmod +x gradlew
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - ./gradlew compileJava
      - ./gradlew processResources
      - ./gradlew classes
      - ./gradlew bootJarMainClassName
      - ./gradlew bootJar
      - ./gradlew jar
      - ./gradlew assemble
      - ./gradlew compileTestJava
      - ./gradlew processTestResources
      - ./gradlew testClasses
      - ./gradlew check
      - ./gradlew clean build
artifacts:
  files:
    - build/libs/finAPI-0.0.1-SNAPSHOT.jar
  discard-paths: yes
